### ISSUE TITLE
テストを網羅的に記述する

### ISSUE THREAD

**Issue by yk-saito** [unchain-tech/ETH-NFT-Game#2]
- [x]  提出物が学習コンテンツ通りに作成されているかの動作確認ができる、テストスクリプトを追加する
- [x] キャラクターmint、攻撃、ターン、game overなど教材に明示的に記されている機能は全てテストする
- [x]  https://github.com/shiftbase-inc/UNCHAIN-test-submissions から実行できるようにする

**Comment by honganji** [comment]
テストスクリプトの追加と、[自動テスト](https://github.com/shiftbase-inc/UNCHAIN-test-submissions)からの実行ができるようにしました。
